BASE_DIR: '/content/drive/MyDrive/projects/ComputerVision/identifier_system_by_face'
TRAIN_DATASET_DIR: os.path.join(BASE_DIR, 'train_dataset')
TEST_DATASET_DIR: os.path.join(BASE_DIR, 'test_dataset')
IMG_FOLDER: 'img'
FACE_FOLDER: 'faces'
EMBEDDING_FOLDER: 'embeddings'